### PR TITLE
Introduce implicit alias `system` for system perl

### PR DESCRIPTION
**Pull request by happy-barney**
It allows usage like:
 - perlbrew use system
 - perlbrew lib create system@foo

### CODE REVIEW

**Comment by gugod** [comment]
@happy-barney are you aware of the `off` command ? (It's part of bash integration)

The word 'system' used to mean exactly the same as what you are proposing here, but it was deprecated a while ago and no longer have a special meaning since then: See: https://perlbrew.pl/Release-0.29.html

If we introduce such special keyword, we might want to review whether there are several hidden assumption here and there. It also makes sense not to "control" something that is not installed by perlbrew itself. Or to put it in a different way: System perl is there to run those softwares for OS itself, while perlbrew manages perl installations that runs your application.

What use cases are you imagining that would be improved by having a way to create a "lib" for system perl ?

**Comment by happy-barney** [comment]
I'm aware of that. This is not about control, this is about being able to create  and manage multiple libs without installing any perl. 

Use case will be for example command `dzil` (see #642)

**Comment by gugod** [comment]
@happy-barney I'm more keen to know why *you* need this, and how that applies to everyone else :) Sure the new `dzil` command would be consuming this new set of feature change, but that alone wouldn't be a selling point, IMHO. I'm not saying that PRs needs to be self-appealing though. I'm saying that when it comes to release a new version that includes all this, I would want add some explaination about contextual information on why we revert our previous decision and bringing back the special meaning of the word "system" instead of just saying: "In this version, The word "system" is now special, good luck and have a nice day."

I feel like the purpose of managing multiple "lib" for system perl can also be achieved without introducing a special keyword. We simply make existing command work with perlbrew is off. Such as:

```
perlbrew off # use system perl

# TODO: these ERRORed for the moment.
perlbrew lib create dev      # create a "dev" lib to be used with system perl
perlbrew lib create @dev  # ditto

perlbrew off
perlbrew use @dev # switch to the "dev" lib of "current" perl -- which is system perl.
```

The command `perlbrew lib create <name>` already have the semantic of "creating a lib of given name under current perl" -- whatever "current perl" might be. Now it just refuse to run if the "current perl" is system perl. I feel like this might be a better option, because there's no need to introduce a special name, and perhaps a dozen of branches in perlbrew.pm to deal with this special name.

**Comment by happy-barney** [comment]
I don't need exactly alias `system`, I would like to have option to choose library internally by command `dzil`(or any other similar in future).

Using `system` is just my first approach.

Allowing `lib` and `use` to recognize empty perl as system perl looks like better solution.

What about option `--system` that will act like executing `perlbrew off` first ?

```
perlbrew lib create --system @dev 
perlbrew use --system @dev 
```

Instead of
```
perlbrew off
perlbrew lib create @dev 

perlbrew off
perlbrew use @dev 
```

**Comment by gugod** [comment]
Hi,

I'm just closing this PR for good and leaving this comment for the record.

I think we should stop persuing this concept and leave so call "system perl" outside of perlbrew realm. Introducing that dimenion (back) to perlbrew lead too many unknowns and it probaly isn't worth it since users can use switch off perlbrew if they really want system perl.

**Comment by happy-barney** [comment]
ok, I mostly agree

there is only one use case left where I still believe usage of system perl will be beneficial (at least how I use it) - local lib for dzil (to share all required plugins). That case may be handled by plain `perlbrew dzil` command - I have basic idea but no time yet to make Pr.

**Pull request closed without merging**
