### PR TITLE
fix the path to fish config

### PR DESCRIPTION
**Pull request by chee**
it's in ~/.config rather than ~/config

### CODE REVIEW

**Comment by chee** [comment]
i don't understand the perlcritic failure

**Comment by gugod** [comment]
@chee thank you  .. :) Would you elaborate hon ow fishrc has been broken ? For what I see that path has been like that since the very beginning.

cc @yanick , @gucchisk

**Comment by gugod** [comment]
> i don't understand the perlcritic failure

it report something that is not related to your change -- for now it can be ignored.

**Comment by chee** [comment]
> @chee thank you .. :) Would you elaborate hon ow fishrc has been broken ? For what I see that path has been like that since the very beginning.
> 
> cc @yanick , @gucchisk

yes. it tells you to do this:

> Append the following piece of code to the end of your ~/config/fish/config.fish 

but your fish config is, by default, in `~/config/fish/config.fish`. i guess it might also be in `$XDG_CONFIG_HOME/fish/config.fish`

**Pull request merged**
