### PR TITLE
Fix perlbrew.fish syntax error and forgotten change unsetenv to set -eg

### LINKED ISSUE #697: perlbrew.fish has some bugs
While using the newest version of perlbrew in combination with my fish-shell. I stumbled over a few bugs in the `perlbrew.fish` file.
1. The combination of the `-e` and the `-u` argument are not allowed for `set`, therefore `set -eug`throws an error
2. The `__source_init` function in `perlbrew.fish` doesn't change the line `unsetenv PERLBREW_LIB` to `set -eg PERLBREW_LIB`

### PR DESCRIPTION
**Pull request by moseschmiedel**
Fix #697

### CODE REVIEW

**Comment by moseschmiedel** [comment]
Will you do a release at some time in the future with these changes?
 There is also already another PR that requests the same changes #708.

**Comment by gugod** [comment]
@moseschmiedel  I see... thanks for the reminder. I'll find some time to make aa new release this week.

**Comment by moseschmiedel** [comment]
No worries. I don't want to put pressure in you. Thank you for taking the time building and maintaining such a great project.

**Comment by jimbobmcgee** [comment]
@gugod - Do you have any feeling how long it takes for an upstream distro (esp. Fedora) takes to apply your releases?  As of 27-Jan-2021, F32 currently pushes v0.88 from its `dnf` repository (which doesn't include this), and `perlbrew` won;t `self-update` if managed by system-wide `dnf`.

In the meantime, I have patched the `perlbrew.fish` script manually -- since `perlbrew` generates this file itself (rather than pushing it as a package artefact), should I assume this gets overwritten when the upstream package updates, and that any existing version is not backed up?

**Comment by gugod** [comment]
@moseschmiedel  Thanks for your contribution. This PR is released as part of 0.90: https://perlbrew.pl/Release-0.90.html

**Comment by gugod** [comment]
@jimbobmcgee  i have very little insight about how perlbrew get packaged in various system, but I imagine `perlbrew.fish` needs to be manually updated by users.

Assuming  PERLBREW_ROOT is set, you should be able to run `perlbrew init` again to re-generate `perlbrew.fish` under `$PERLBREW_ROOT / etc / `.

BTW I've enabled the "Discussion" on GitHub: https://github.com/gugod/App-perlbrew/discussions  Perhaps we could take further discussions to there since this PR itself is concluded. :)

**Pull request merged**
