### PR TITLE
command dzil - #639

### PR DESCRIPTION
**Pull request by happy-barney**
New command dzil - caching Dist::Zilla wrapper

### CODE REVIEW

**Comment by happy-barney** [comment]
This is how I imagine command dzil to work though I'm struggling little bit with tests - no idea (yet) how to test it without installing Dist::Zilla and author dependencies.

**Comment by happy-barney** [comment]
First, this is first working draft, it's not intended for merge (yet), just to show an idea and discuss usefulness.

Ad help: thanks, this I completely forgot to mention this :-). There will be two commands:
- `perlbrew help dzil` will print perlbrew help
- `perlbrew dzil help` will print dzil help

Ad system:
That's remnant from other branch (branch where I started to play with perlbrew) :-)
Basically, it's an alias for system perl. I wanted to have "stable" installation available. I'll extend this pull request.

**Comment by gugod** [comment]
@happy-barney Thanks for the explanation. Let me mark this PR as WIP then, since it is still a work in progress. Feel free to remove that WIP label once you're finished.

Regarding giving the name "system" or "stable" some special meaning -- Although I prefer not to have special names, I'm not against this idea. (when perlbrew started,  "system" was special name too.) If we do end up doing this, I wish it to be clearly documented as well.

**Comment by gugod** [comment]
I'm closing this PR due to the lack of activity. In case it is still anyone's interest, feel free to re-open it.

**Pull request closed without merging**
